# run_cpp.yml
tasks:
  - label: "Build and Run hello_world.cpp"
    type: shell
    command: g++ hello_world.cpp -o hello_world.exe
    group: {
      "kind": "build",
      "isDefault": true
    }
    problemMatcher: []
    dependsOn: []
    presentation: {
      "reveal": "always",
      "panel": "new"
    }
  - label: "Run hello_world.exe"
    type: process
    command: hello_world.exe
    group: {
      "kind": "test",
      "isDefault": true
    }
    dependsOn: "Build and Run hello_world.cpp"
    presentation: {
      "reveal": "always",
      "panel": "new"
    }
